version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=oj_project.settings
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=oj_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
