# Generated by Django 5.2.4 on 2025-07-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_submission_error_submission_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
