# Generated by Django 5.2.4 on 2026-04-12 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_submitted_at_submission_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-created_at'], name='authenticat_user_id_75103a_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'verdict'], name='authenticat_problem_82fb2c_idx'),
        ),
    ]
